name: Build and Deploy Flutter Web to gh-pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Instalar dependencias
        run: flutter pub get
        working-directory: project

      - name: Compilar Flutter Web
        run: flutter build web --release
        working-directory: project

      - name: Copiar archivos a public/
        run: |
          mkdir public
          cp -r project/build/web/* public/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
